### ISSUE TITLE
Can't distinguish commands from output

### ISSUE THREAD

**Issue by negz** [crossplane/docs#317]
### What's Wrong?

In some (possibly all?) command snippets It's difficult to quickly visually distinguish which lines are commands and which are output.  For example at https://docs.crossplane.io/v1.11/getting-started/provider-aws/ I see:

<img width="919" alt="Screenshot 2023-02-01 at 12 29 44 PM" src="https://user-images.githubusercontent.com/1049349/216156581-08e7626e-3083-460b-a596-a2af78e8d681.png">

I do note that when I click the "copy" button it only copies the command input, which is useful but was not the behaviour I expected. My intuition was that the copy button would copy the entire content of the code block.

I believe it's fairly common to see the command prefaced with a `$` to give a visual distinction. Is this something we should do?

**Comment by plumbis** [comment]
Using CSS we can put a `$` before a command.
![Screenshot 2023-02-02 at 1 07 51 PM](https://user-images.githubusercontent.com/10537576/216408347-a377325e-8a06-4be8-8d4d-9e4017a5fbbf.png)

Because it's with CSS it's not a standard character and can't be selected.
![Screenshot 2023-02-02 at 1 07 55 PM](https://user-images.githubusercontent.com/10537576/216409242-f52eaeb4-52a1-4ffc-ae54-1b1e524f06f1.png)

It also isn't copied with the copy to clipboard button.

This specifically is looking for code blocks that use ` ```shell ` so it won't affect YAML
![Screenshot 2023-02-02 at 1 08 14 PM](https://user-images.githubusercontent.com/10537576/216410457-7e63045d-3d0b-494e-b7b3-55974b22269b.png)

There are a number of existing outputs that have prompts in them that need to be cleaned up, before doing that I wanted to see if you are okay with this proposed solution.

**Comment by negz** [comment]
Yes, that sounds great. Thanks!
