### ISSUE TITLE
Style guide references

### ISSUE THREAD

**Issue by negz** [crossplane/docs#322]
### What's Missing?

The style guide is currently a WIP, and thus includes some requirements without any attached rationale. Including links to the "why" behind our requirements will help contributors understand them. If contributors understand our requirements they are more likely to buy into them, as opposed to simply being forced to comply with them.

Some things that came up during review of https://github.com/crossplane/docs/pull/298 that were unfamiliar to me:

* Why we limit sentences to 25 words specifically. I found https://insidegovuk.blog.gov.uk/2014/08/04/sentence-length-why-25-words-is-our-limit/ to be the most compelling and detailed explanation of this rule.
* Why we use sentence case headings rather than title case. We have a link explaining what they are, but not why we picked them. My understanding is that we did so because they're the standard approach for documentation and technical writing.
* Why we require contractions - https://developers.google.com/style/contractions.
* Why we prefer active voice. We already have a link for this, but I feel https://developers.google.com/style/voice does a better job of explaining why it's important in the context of documentation.
* Why we avoid latin abbreviations. I can't immediately find the rationale for this. The style guides I checked all seem to say to avoid them but not why.

I know we're planning to adopt Vale to address a lot of this, and that Vale includes links to style guides such as Google's. I like this approach of adopting an upstream style guide rather than writing our own. That said, I believe it will be worth keeping a small document to "decorate" the upstream guide(s) to cover cases where they don't explain the rationale behind a requirement.

**Comment by plumbis** [comment]
The short answer to most of these points is "It makes it easier for an international audience to read" (in general) and all for all readers to comprehend new technical content. 

Writing is entirely subjective but there are some [objective measures to measure difficulty](https://en.wikipedia.org/wiki/Readability#Popular_readability_formulas). Gitlab implements [Flesch Kincaid grade level test](https://docs.gitlab.com/ee/development/documentation/testing.html#vale-readability-score). Vale supports [readability testing](https://github.com/errata-ai/readability), but the tests I've run against the Crossplane docs but there is too much jargon and too many technical terms that are polysyllabic technical terms.  This is across multiple readability tests.


To specific points:
> I like this approach of adopting an upstream style guide rather than writing our own

100% agree. The customizations are entirely focused around [spell checking jargon](https://github.com/upbound/vale/blob/main/styles/Upbound/spelling-exceptions.txt). Vale today implements a combination of multiple style guides. Over the last six months I've been pruning duplicate rules, removing unhelpful rules or expanding rules we need specifically for Crossplane. This is why we haven't deployed Vale yet. After the v1.11 reorg and rewrites I feel much more confident that Vale is ready to be deployed without too many false positives. 

>Why we limit sentences to 25 words specifically.

Sentence length is one of the easiest ways to improve readability. Shorter sentences [improve SEO](https://readable.com/blog/what-is-the-best-sentence-length-for-seo/). There are lots of conflicting rules on the number of words in a sentence. Some research cites a [specific number](https://sites.utexas.edu/legalwriting/2021/05/01/sentence-length). Some references [suggest varying sentences](https://www.niu.edu/writingtutorial/style/sentence-structure.shtml). Varied lengths are better for prose or non-technical writing.  Why 25 words? Because we need to draw the line somewhere. So far I'm yet to find a situation where this guideline has made the writing worse.  If there is a location where it can't happen we can always disable the Vale rule for that sentence. 

> Why we use sentence case headings

There is [no global standard](https://en.wikipedia.org/wiki/Title_case#Rules). Why do we use sentence case? Because that's the common "modern" writing style. It's makes writing [more casual](https://uxdesign.cc/title-case-vs-sentence-case-in-ux-writing-212087192261) and approachable.

> Why we require contractions

[Google](https://developers.google.com/style/contractions), [Microsoft](https://learn.microsoft.com/en-us/style-guide/word-choice/use-contractions) and [Gitlab](https://docs.gitlab.com/ee/development/documentation/styleguide/index.html#contractions) require contractions. The primary reason is that reading the a phrase like `do not` vs `don't` can have accidental reader oversight. Readers can omit the `not` in `do not`. There is no ambiguity with `don't`.

> Why we prefer active voice 

This is a standard of all technical and journalistic writing. It leads to more concise and direct writing. It makes translation much easier.

> Why we avoid latin abbreviations

The primary reason is that it makes reading more difficult for international readers, particularly those coming from non-Latin or Germanic languages.  Beyond that there are three common Latin phrases in writing:
* `etc` - "et cetera," meaning "and the others". Either exclude for brevity or list out the others to be precise.
* `e.g.` - "exempli gratia," meaning "for the sake of an example." Say "For example,"
* `i.e` - "id est"  meaning "that is". It's used to clarify writing. Just clarify in the first place, this indicates imprecise writing.

I'd also encourage you to take a look at the current [Upbound/Vale](https://github.com/upbound/vale) repo for a list of enabled rules. Suggestions are always welcome but the goal here is to leverage existing definitions that have been [widely used ](https://vale.sh/types/style/).

**Comment by negz** [comment]
Thanks @plumbis - this level of context is really useful. I do think it would be helpful to add it to the style guide (as a supplement to the information that's already linked from Vale). If I'm asking (after having tried at least briefly to educate myself) others will probably ask too.

**Comment by plumbis** [comment]
I'm in the process of rebuilding/updating the vale repo. I'll open an PR/Issue soon to detail this but my proposal is:

1. Add [upbound/vale](https://github.com/upbound/vale) as a submodule to the docs repo (week of Feb 20)
2. Document the collection of vale libraries in use in the contrib guide (week of Feb 20 or Feb 27)
3. Enable vale as a non-block check against files submitted in PRs. This will flag vale errors but won't block PRs. This improves contribution quality while we continue to build the Crossplane specific exceptions. (week of Feb 27)
4. Target 1.12 as a "go live" for Vale checking as a blocking PR check.

This is probably a larger conversation for the community but I want to get your opinion on this first.

**Comment by jeanduplessis** [comment]
This sounds like a reasonable approach to me. 👍🏻

**Comment by plumbis** [comment]
Vale is now an active CI check. Closing as completed.
