### ISSUE TITLE
Deduplicate or reconcile Introduction and Terminology pages

### ISSUE THREAD

**Issue by negz** [crossplane/docs#327]
### What's Missing?

https://docs.crossplane.io/v1.11/getting-started/introduction/
https://docs.crossplane.io/v1.11/concepts/terminology/

There's a lot of redundancy in these two pages. They define common Crossplane terms, but do so using different language. I think we should either deduplicate them or update them such that the terminology page is a more detailed version of the introduction page. The terminology page also has elements of "style guide" - it talks about how to use certain Crossplane terms. That should probably be moved into part of the docs contribution guide.

**Comment by negz** [comment]
This is something I'd like to work on - I'm strongly opinionated about the nuance of how our core concepts are communicated.

**Comment by plumbis** [comment]
Agreed, this is mainly due to time constraints with the reorg and release. I was trying to not delete things without proper review first. 

I think we should remove _Terminology_ and just have two things:
1. Intro covering the high level for people that are new
2. Thorough /concepts pages for each Crossplane kind. This would be the in-depth reference for that individual component.

**Comment by plumbis** [comment]
Fixed in #475
