### ISSUE TITLE
Add linting job for markdown content structure

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane/docs#364]
To ensure consistency in the structure of our markdown documents, it will be advantageous to use something like https://github.com/DavidAnson/markdownlint to lint the content of PRs and ensure consistent structure.

**Comment by jeanduplessis** [comment]
@plumbis thoughts on this?

**Comment by plumbis** [comment]
I think this is a great idea! Much like Vale, there is a ton of stuff that will need to be cleaned up.

**Comment by plumbis** [comment]
I'm going to close this as "won't do".

This puts an added burden on authors and I'm already at risk of being murdered in my sleep because of Vale. 

Our use of shortcodes (e.g., `{{<hover ... >}}`) are all considered violations by markdownlint. 

There would be value in some code readability like enforcing lines around headings and code blocks but I don't think the ROI is worth it.
