### ISSUE TITLE
API documentation for core types like `Composition`

### ISSUE THREAD

**Issue by negz** [crossplane/docs#440]
### What's Missing?

I'd like to find detailed API documentation for core types like `CompositeResourceDefinition`, `Provider`, and `Composition` somewhere under https://docs.crossplane.io. I imagine these would be auto-generated from our CRDs or type definitions.

Some prior art:

* https://marketplace.upbound.io/providers/upbound/provider-aws/v0.34.0/resources/accessanalyzer.aws.upbound.io/Analyzer/v1beta1
* https://doc.crds.dev/github.com/crossplane/crossplane
* https://knative.dev/docs/serving/reference/serving-api/
* https://istio.io/latest/docs/reference/config/networking/proxy-config/

I feel that this documentation should be a "first class citizen" of the Crossplane documentation. It's fairly critical, so I'd rather not defer it to a third party like doc.crds.dev or marketplace.upbound.io.

**Comment by plumbis** [comment]
Looking into this I think we can take the [yaml](https://github.com/crossplane/crossplane/tree/master/cluster/crds) defining the CRDs and use [Hugo data templates](https://gohugo.io/templates/data-templates/) to extract it and put it in a layout. 

The bigger lift will be implementing the html/css design.

**Comment by plumbis** [comment]
This also means we probably will need to extend the c/c release process to include a PR with an updated yaml. 

The alternative would be a cron job or build script on the docs that pulls from c/c

**Comment by plumbis** [comment]
Currently in development.
Preview: https://deploy-preview-610--crossplane.netlify.app/v1.14/crds/

TODO: 

- [ ]  Make the minus icon white instead of black and match size of plus
- [ ]  Add links to the specific elements and expand the menus as needed when loading an anchor link
- [ ]  Support dark mode
- [ ]  in-page search and filtering, including required only filter
- [ ]  add sorting buttons
- [ ]  fix lock and environmentconfig types that don't have top-level spec attribute.
- [ ] add 80px left-side gutter
- [ ] confirm mobile and responsive support

**Comment by jbw976** [comment]
cooooool @plumbis!! nice to see core APIs making their way into the docs!

this is a great start dude 💪, and i understand this is a super early preview of this functionality, so please take all the below observations as constructive towards a final polished goal and not a criticism of the work so far! keep it up 📈 🤩 

* looks like we may not be diving all the way through the schema to display the entire structure of each API. e.g. check out Composition -> `spec.environment.patches` on the [preview site](https://deploy-preview-610--crossplane.netlify.app/v1.14/crds/) which stops at saying it's `[]object`, but doesn't list anything deeper than that
  * Compare this to what [Composition API on doc.crds.dev](https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Composition/v1@v1.14.1#spec-environment-patches) displays.  That shows multiple subfields underneath that we're missing. I think this issue is widespread for all `[]object` fields, so it may have a general fix.
* I also like the direct/deep linking that doc.crds.dev supports, allowing you to share a link that takes you directly to a particular subfield - can we consider that?
* what order are the APIs listed in? they don't appear to be strict alphabetical
* i'm torn on the default being to expand just the next level when clicking on a + box. this can make it tedious with a lot of clicking if you're exploring a lot of an API, but is probably right for the casual use case. I wonder if there could be a shortcut to expand the entire graph of an API completely, including all its nested sub levels?
  * a collapse all shortcut could be useful here too
* expanding fields can sometimes scroll the page too, which is jarring and can make you lose your place visually, forcing you to look around again for the field you just expanded
* definitely like the ideas around filtering, esp. the "required only" filter. I wonder if there are other experiences we can enable for folks to quickly find the fields they are looking for...

**Comment by plumbis** [comment]
> direct/deep linking
> 
> looks like we may not be diving all the way through the schema to display the entire structure of each API
> 
> what order are the APIs listed
>
> could be a shortcut to expand the entire graph of an API  + a collapse all shortcut

Yup, all these are listed in the [checklist](https://github.com/crossplane/docs/issues/440#issuecomment-1811048776)

For order it will default to sorted by Kind with options to sort by version and group. 

> expanding fields can sometimes scroll

Good call out. I'll make sure this is covered. 

> filtering, esp. the "required only" filter. I wonder if there are other experiences 

I would love opinions here. Depending on what they are maybe feasible for v1.0 otherwise an easy add on later.

**Comment by jbw976** [comment]
> I would love opinions here

one UX i can imagine, that you may already be thinking of, would be a box you can start typing a field name in.  as you're typing, the API list below is getting filtered to just fields that match that string.  hopefully this could work with paths, e.g. typing in `spec.forProvider.fooField`. Also, it may be good (but not fully sure yet) to preserve context to these fields within the view, i.e. show the tree/path to get to that specific field as opposed to just showing that field in isolation.

> Yup, all these are listed in the checklist

I didn't see the "`[]object` not being probed" issue explicitly listed within the existing checklist, so wanted to make sure that wasn't falling by the wayside 😉

**Comment by plumbis** [comment]
The `[] object` problem is " fix lock and environmentconfig types that don't have top-level spec attribute"

I'm hard coding on `spec` as the top level attribute and those two types don't have a `spec` so it breaks.

**Comment by jbw976** [comment]
I'm not sure it is the same problem @plumbis because the example I first found of it was for the `Composition` type, path `spec.environment.patches`.  That type has a top level `spec` attribute, so there's no problem there.

The problem is deeper down in `spec.environment.patches` which is empty.  doc.crds.dev shows a lot of fields/content there that we are not showing: https://doc.crds.dev/github.com/crossplane/crossplane/apiextensions.crossplane.io/Composition/v1@v1.14.1#spec-environment-patches

Are you sure they are the same problem? 🤔

**Comment by plumbis** [comment]
> Composition type, path spec.environment.patches

🤔 interesting. That's a different problem than the one I know about with  lock and environmentconfig. I'll make sure that's addressed. Thanks!

**Comment by plumbis** [comment]
@jbw976 you were seeing extra scrolling on expansion, can you take a look at the latest [branch preview](https://api--crossplane.netlify.app/v1.14/crds/) and tell me if you still see it?

**Comment by jbw976** [comment]
Confirmed @plumbis, I do not see that scrolling on expansion behavior anymore!! 💪

**Comment by plumbis** [comment]
Issue with fonts in Firefox have been fixed
Issue with anchor links and the text copied to the clipboard have been fixed.

Currently no known outstanding bugs.
