### ISSUE TITLE
[Web Bug] - AWS Quickstart

### ISSUE THREAD

**Issue by RinkiyaKeDad** [crossplane/docs#464]
URL: https://docs.crossplane.io/v1.12/getting-started/provider-aws/

Clicking the copy button copies the output also instead of just copying `kubectl get buckets` in this section: https://docs.crossplane.io/v1.12/getting-started/provider-aws/#create-a-managed-resource

**Comment by aroramrinaal** [comment]
Hello @RinkiyaKeDad ,
I do not understand the issue when using the copy button in the section https://docs.crossplane.io/v1.12/getting-started/provider-aws/#create-a-managed-resource 
it is just copying
![Screenshot 2023-06-20 at 9 48 01 PM](https://github.com/crossplane/docs/assets/90490253/68787141-536a-486f-b57a-382cb8f2bdf8)

**Comment by jeanduplessis** [comment]
@RinkiyaKeDad are you referring to this code snippet?

![image](https://github.com/crossplane/docs/assets/492942/57e9b1cc-94e1-4413-82ba-0486b049bebe)

**Comment by aroramrinaal** [comment]
Okay, I think I figured it out that you are referring to this - 
https://docs.crossplane.io/v1.12/getting-started/provider-aws/#create-a-managed-resource

<img width="910" alt="Screenshot 2023-06-21 at 1 04 32 AM" src="https://github.com/crossplane/docs/assets/90490253/afe1ef70-3045-4b69-afca-d8ebcf068b80">
<img width="916" alt="Screenshot 2023-06-21 at 1 04 53 AM" src="https://github.com/crossplane/docs/assets/90490253/fd9bf3eb-91fe-45e2-a70b-8fc4c8ab79c2">

The copy button is copying the whole section along with output instead of `kubectl get buckets`

**Comment by plumbis** [comment]
Good catch @aroramrinaal  and sorry for the problem @RinkiyaKeDad 

I just put in a fix for this in PR #474 and it should be live soon.
