### ISSUE TITLE
[Web Bug] - Azure Quickstart

### ISSUE THREAD

**Issue by iamNoah1** [crossplane/docs#471]
The whole helm install section is missing for the azure quickstart page. 

URL: https://docs.crossplane.io/latest/getting-started/provider-azure/

**Comment by jbw976** [comment]
I think this soon to be merged PR will take care of this @iamNoah1: https://github.com/crossplane/docs/pull/444

The helm install section is included here: https://github.com/crossplane/docs/pull/444/files#diff-12eff2635f4fb9fc7d3846888b085ab50e8d87d42684f4019e597627ef20481eR42

I'll go ahead and close this because I think this will be resolved with that PR, but do let me know if you have other concerns! ✅
