### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by jbw976** [crossplane/docs#472]
### What's Missing?

The crossplane docs used to have a frequently asked questions (FAQs) page, e.g. https://docs.crossplane.io/v1.10/faqs/

It has since been removed though, probably because it was sparse and not all that useful.

We're starting a new blog.crossplane.io blog post series for FAQS and we intend to put each of those highlighted FAQ into the docs.  We should revive a FAQ page in the docs to host these upcoming FAQs 🤓

**Comment by plumbis** [comment]
I'm hesitant to build a new dedicated FAQ page. 

FAQ pages are generally an anti-pattern in docs because they don’t age well. [[1](https://github.com/crossplane/docs/issues/473#issuecomment-1600846871)] [[2](https://www.writethedocs.org/guide/writing/style-guides/?highlight=faq#faqs)] [[3](https://www.writethedocs.org/blog/newsletter-may-2020/?highlight=faq#to-answer-or-not-to-answer-faqs)] [[3](https://d1b14unh5d6w7g.cloudfront.net/1484272161.01.S01Q.JUMBOXXX.jpg?Expires=1687441219&Signature=P9e7pb56T9KAdlsA89gpMPm4qTguICdh5jlJx7LaxnIOsE10MC5jJwPHk9S1VQWC5xb1QvG3qk3-7IYxjmRqbWAdCdurM9cwasQx0Ko7TWwGDnv8p3IspSyP0x~XhCrC-7Fvj0H6yIj-P5feVjUV0FHqP6Nte3KBiAHVXY6baJU_&Key-Pair-Id=APKAIUO27P366FGALUMQ)]

Given that a lot of the problems with the current state of our docs is known, I'd rather work on addressing those first (for example, the ongoing rewrite of the [/concepts](https://github.com/crossplane/docs/issues/450) section) and then come back around to consider an FAQ page. 

I can be convinced, but my opening position is "our FAQs are a result of problems in the existing docs that should be directly addressed".  A concrete example of this is something like error conditions. We don't document most of them so if a user searches the docs for the error they see in the logs there are no results. The first fix for this was with [Provider Conditions](https://docs.crossplane.io/v1.12/concepts/providers/#provider-conditions).

**Comment by plumbis** [comment]
@jbw976 and I talked about this offline and I'm going to close it for now.
