### ISSUE TITLE
"Learn More" Document Access

### ISSUE THREAD

**Issue by ronaldpetty** [crossplane/docs#836]
Not critical, just a request. Could the "Learn More" pdf be moved to just download directly or cleanup the page; versus how its currently hosted (graphics / popups). I think it distracts from the value of quickly learning more about Crossplane.

https://resources.upbound.io/one-pagers/crossplane-overview

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/b6aadb35-0756-4f4e-924c-ba9776895bf7">

**Comment by jbw976** [comment]
Thanks for providing this feedback @ronaldpetty! This particular repo/org is for upstream community Crossplane issues, e.g. issues on https://docs.crossplane.io.

Since this issue is for the experience on upbound.io, would you mind re-opening this issue in https://github.com/upbound/upbound? Unfortunately, GitHub doesn't let you transfer issues across organizations, so you'll have to re-open it there manually.  Thanks for taking the time to provide this info! 🙇‍♂️
